name: Publish .NET Desktop App

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-publish:
    runs-on: windows-latest # 根据你的目标平台选择合适的 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained true # 根据你的目标平台调整

      - name: Upload artifact ArknightsBetting Avalonia
        uses: actions/upload-artifact@v4
        with:
          name: ABA
          path: ${{ github.workspace }}\ArknightsBetting.Avalonia\bin\Release\net8.0\win-x64\publish\
      - name: Upload artifact ArknightsBetting Cli
        uses: actions/upload-artifact@v4
        with:
          name: ABC
          path: ${{ github.workspace }}\ArknightsBetting.Cli\bin\Release\net8.0\win-x64\publish\